export const S = {
  // Layout
  app: {
    display: "flex",
    minHeight: "100vh",
    background: "transparent",
    fontFamily: "'Geist', -apple-system, BlinkMacSystemFont, 'SF Pro Display', sans-serif",
    color: "var(--text-primary)",
  },
  main: { flex: 1, overflow: "auto" },

  // Sidebar
  sidebar: {
    width: 200,
    background: "rgba(8, 14, 26, 0.94)",
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
    borderRight: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    position: "sticky",
    top: 0,
    height: "100vh",
    flexShrink: 0,
  },
  navItem: {
    display: "block",
    width: "100%",
    textAlign: "left",
    padding: "9px 12px",
    border: "none",
    borderRadius: 4,
    cursor: "pointer",
    fontSize: 13,
    letterSpacing: "0.01em",
    background: "transparent",
    transition: "background 0.15s, color 0.15s",
  },

  // Page
  page: { padding: "40px 44px 72px", maxWidth: 900 },
  pageHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 32,
  },
  eyebrow: {
    fontSize: 10,
    color: "var(--accent)",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    fontWeight: 600,
    marginBottom: 6,
    fontFamily: "var(--font-mono)",
  },
  pageH1: {
    fontSize: 30,
    fontWeight: 300,
    color: "var(--text-primary)",
    fontFamily: "'Instrument Serif', Georgia, serif",
    lineHeight: 1.1,
    letterSpacing: "-0.02em",
  },

  // Cards
  heroCard: {
    background: "var(--surface)",
    borderRadius: "var(--radius-lg)",
    padding: "26px 30px",
    marginBottom: 12,
    border: "1px solid var(--border)",
    borderLeft: "2px solid var(--accent)",
    boxShadow: "var(--shadow-sm), inset 2px 0 20px rgba(59,130,246,0.04)",
  },
  catGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))",
    gap: 8,
    marginBottom: 12,
  },
  catCard: {
    background: "var(--surface)",
    borderRadius: "var(--radius-md)",
    padding: "16px 16px",
    border: "1px solid var(--border)",
    boxShadow: "var(--shadow-sm)",
    transition: "border-color 0.2s, box-shadow 0.2s",
  },
  twoUp: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  panel: {
    background: "var(--surface)",
    borderRadius: "var(--radius-md)",
    padding: "20px 22px",
    border: "1px solid var(--border)",
    boxShadow: "var(--shadow-sm)",
  },
  panelLbl: {
    fontSize: 9,
    fontWeight: 600,
    color: "var(--text-tertiary)",
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    marginBottom: 14,
    fontFamily: "var(--font-mono)",
  },

  // Goals page
  catStrip: {
    background: "var(--surface)",
    borderRadius: "var(--radius-md)",
    padding: "14px 18px",
    marginBottom: 16,
    border: "1px solid var(--border)",
    display: "flex",
    gap: 16,
    overflowX: "auto",
  },
  tabRow: { display: "flex", borderBottom: "1px solid var(--border)", marginBottom: 20 },
  tab: {
    background: "none",
    border: "none",
    padding: "10px 16px",
    fontSize: 13,
    cursor: "pointer",
    transition: "color 0.15s",
  },
  mCard: {
    background: "var(--surface)",
    borderRadius: "var(--radius-md)",
    padding: "16px 18px",
    border: "1px solid var(--border)",
  },

  // Buttons
  addBtn: {
    background: "var(--accent)",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "9px 18px",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    transition: "opacity 0.15s, transform 0.15s var(--easing-spring)",
    boxShadow: "0 2px 14px rgba(59,130,246,0.35)",
  },
  advBtn: {
    background: "var(--green)",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "9px 20px",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    boxShadow: "0 2px 18px rgba(34,197,94,0.40)",
    transition: "opacity 0.15s, transform 0.15s var(--easing-spring)",
  },
  delBtn: {
    background: "none",
    border: "none",
    color: "var(--text-tertiary)",
    fontSize: 14,
    cursor: "pointer",
    padding: "2px 6px",
    lineHeight: 1,
    flexShrink: 0,
    borderRadius: 3,
    transition: "color 0.1s",
  },

  // Setup
  setupWrap: {
    minHeight: "100vh",
    background: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  setupCard: {
    background: "var(--surface)",
    borderRadius: "var(--radius-xl)",
    padding: "44px 44px 40px",
    width: "100%",
    maxWidth: 500,
    border: "1px solid var(--border)",
    boxShadow: "var(--shadow-md)",
    animation: "scaleIn 0.4s var(--easing-spring)",
  },
  stepRow: { display: "flex", justifyContent: "space-between", marginBottom: 40, position: "relative" },
  setupH: {
    fontSize: 30,
    fontWeight: 300,
    color: "var(--text-primary)",
    fontFamily: "'Instrument Serif', Georgia, serif",
    lineHeight: 1.2,
    marginBottom: 10,
    letterSpacing: "-0.02em",
  },
  setupDesc: {
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.6,
    marginBottom: 24,
  },
  bigInput: {
    width: "100%",
    fontSize: 22,
    fontWeight: 300,
    color: "var(--text-primary)",
    border: "none",
    borderBottom: "1px solid var(--border)",
    padding: "8px 0",
    outline: "none",
    background: "transparent",
    fontFamily: "'Instrument Serif', Georgia, serif",
    marginBottom: 28,
    transition: "border-color 0.2s",
  },
  catGoalRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    background: "var(--surface-2)",
    borderRadius: 6,
    border: "1px solid var(--border)",
  },
  catGoalLbl: { display: "flex", alignItems: "center", gap: 8, width: 126, flexShrink: 0 },
  inlineInput: {
    flex: 1,
    background: "transparent",
    border: "none",
    padding: "4px 0",
    fontSize: 13,
    color: "var(--text-primary)",
    outline: "none",
  },
  nextBtn: {
    width: "100%",
    background: "var(--accent)",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "13px",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    marginTop: 4,
    transition: "opacity 0.15s, transform 0.15s var(--easing-spring)",
    boxShadow: "0 2px 16px rgba(59,130,246,0.35)",
  },
  backBtn: {
    background: "transparent",
    color: "var(--text-secondary)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "12px 18px",
    fontSize: 13,
    cursor: "pointer",
    transition: "background 0.15s, color 0.15s",
  },
  rankPill: {
    padding: "5px 13px",
    borderRadius: 4,
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    transition: "all 0.2s var(--easing-spring)",
    letterSpacing: "0.06em",
    fontFamily: "var(--font-mono)",
  },

  // Add sheet / forms
  fLbl: {
    display: "block",
    fontSize: 9,
    fontWeight: 600,
    color: "var(--text-tertiary)",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    marginBottom: 6,
    fontFamily: "var(--font-mono)",
  },
  fInput: {
    width: "100%",
    background: "var(--surface-2)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "10px 12px",
    fontSize: 13,
    color: "var(--text-primary)",
    outline: "none",
    transition: "border-color 0.2s, box-shadow 0.2s",
  },
  ghostBtn: {
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "8px 14px",
    fontSize: 12,
    color: "var(--text-secondary)",
    cursor: "pointer",
    transition: "background 0.15s, color 0.15s, border-color 0.15s",
  },

  // Toast
  toast: {
    position: "fixed",
    bottom: 28,
    right: 28,
    zIndex: 999,
    background: "var(--surface)",
    border: "1px solid var(--accent)",
    color: "var(--text-primary)",
    padding: "10px 18px",
    borderRadius: 8,
    fontSize: 12,
    fontWeight: 500,
    boxShadow: "var(--shadow-lg), 0 0 20px rgba(59,130,246,0.25)",
    animation: "fadeUp 0.25s var(--easing-spring)",
    fontFamily: "var(--font-mono)",
    letterSpacing: "0.02em",
  },
};
